### ISSUE TITLE
Marking Checklist

### ISSUE THREAD

**Issue by coderaayush** [SomtoUgeh/roadchillz#8]
**Deployment**
- [x] Requirements file is included and contains the correct packages 3
- [x] Database / migrations files not included 1
- [x] Population script works and contains useful example data 2
- [x] Application can be deployed on marker's own machine 3

**Functionality**

- [x] Main functionality has been implemented reflecting the design 10
- [x] Application is bug-free / no error messages occur 3
- [x] Application includes some Javascript / JQuery / AJAX 3

**Look and Feel**

- [x] Polished / refined interface, not clunky 3
- [x] Uses a responsive CSS framework 2
- [x] If browser window size changed, is the change handled neatly? 1

**Code**

- [x] Code contains helper functions/classes (if required) 4
- [x] Code is readable, clear and commented where appropriate 4
- [x] CSS and Javascript kept separate from templates (i.e., not inline) 4
- [x] No repetition of code blocks in the views or templates 3
- [x] Unit tests are included – 4 unique unit tests 4
